const myBooks = [
    //PERCY JACKSON & THE OLYMPIANS 
    { series: "Percy Jackson", title: "The Lightning Thief", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/percy-jackson/1.JPG", status: "popular", tags: ["Fantasy", "Mythology", "Teenagers"], description: "Percy discovers he's a demigod and son of Poseidon.", summary: "Twelve-year-old Percy Jackson is on the most dangerous quest of his life. With the help of a satyr and a daughter of Athena, Percy must journey across the United States to catch a thief who has stolen the original weapon of mass destruction — Zeus’ master bolt." },
    { series: "Percy Jackson", title: "The Sea of Monsters", author: "Rick Riordan", paws: "🐾🐾🐾🐾", image: "pictures/books/percy-jackson/2.JPEG", status: "hidden", tags: ["Fantasy", "Mythology", "Teenagers"], description: "The quest for the Golden Fleece to save Camp Half-Blood.", summary: "Percy’s seventh-grade year has been surprisingly quiet. But when a game of dodgeball becomes a death match against a gang of cannibal giants, things get... complicated." },
    { series: "Percy Jackson", title: "The Titan's Curse", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/percy-jackson/3.JPEG", status: "hidden", tags: ["Fantasy", "Mythology", "Teenagers"], description: "Percy must find the missing goddess Artemis.", summary: "When Percy Jackson receives an urgent distress call from his friend Grover, he immediately prepares for battle. He knows he'll need his powerful demigod allies at his side." },
    { series: "Percy Jackson", title: "The Battle of the Labyrinth", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/percy-jackson/4.JPEG", status: "hidden", tags: ["Fantasy", "Mythology", "Teenagers"], description: "Navigating the deadly maze of Daedalus.", summary: "Percy Jackson isn't expecting freshman orientation to be any fun. But when a mysterious mortal acquaintance appears on campus followed by demon cheerleaders, things quickly go from bad to worse." },
    { series: "Percy Jackson", title: "The Last Olympian", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/percy-jackson/5.JPEG", status: "new", tags: ["Fantasy", "Mythology", "Teenagers"], description: "The final battle for Olympus in hidden York City.", summary: "All year the half-bloods have been preparing for battle against the Titans, knowing the odds of victory are grim. Kronos’s army is stronger than ever." },

    //HEROES OF OLYMPUS
    { series: "The Heroes of Olympus", title: "The Lost Hero", author: "Rick Riordan", paws: "🐾🐾🐾🐾", image: "pictures/books/Heros_olympus/1.JPEG", status: "hidden", tags: ["Fantasy", "Mythology", "Teenagers"], description: "Jason, Piper, and Leo discover a hidden camp.", summary: "Jason has a problem. He doesn't remember anything before waking up on a scHeros_olympusl bus holding hands with a girl named Piper." },
    { series: "The Heroes of Olympus", title: "The Son of Neptune", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/Heros_olympus/2.JPEG", status: "hidden", tags: ["Fantasy", "Mythology", "Teenagers"], description: "Percy arrives at a Roman camp with no memory.", summary: "Percy is confused. When he awoke after his long sleep, he didn't know much more than his name." },
    { series: "The Heroes of Olympus", title: "The Mark of Athena", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/Heros_olympus/3.JPEG", status: "hidden", tags: ["Fantasy", "Mythology", "Teenagers"], description: "The Greek and Roman demigods finally unite.", summary: "Annabeth is terrified. Just when she's about to be reunited with Percy—after six months of being apart—it looks like Camp Jupiter is preparing for war." },
    { series: "The Heroes of Olympus", title: "The House of Hades", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/Heros_olympus/4.JPEG", status: "popular", tags: ["Fantasy", "Mythology", "Teenagers"], description: "A journey through the darkest parts of the Underworld.", summary: "At the conclusion of The Mark of Athena, Annabeth and Percy tumble into a pit leading straight to Tartarus." },
    { series: "The Heroes of Olympus", title: "The Blood of Olympus", author: "Rick Riordan", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/Heros_olympus/5.JPEG", status: "hidden", tags: ["Fantasy", "Mythology", "Teenagers"], description: "The final war against the Earth Mother, Gaea.", summary: "The Greek and Roman demigods must defeat the giants before Gaea wakes up fully." },

    //HARRY POTTER
    { series: "Harry Potter", title: "Philosopher's Stone", author: "J.K. Rowling", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/HP/1.JPEG", status: "hidden", tags: ["Fantasy", "Magic", "Teenagers"], description: "The boy who lived starts his journey.", summary: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive." },
    { series: "Harry Potter", title: "Chamber of Secrets", author: "J.K. Rowling", paws: "🐾🐾🐾🐾", image: "pictures/books/HP/2.JPEG", status: "hidden", tags: ["Fantasy", "Magic", "Teenagers"], description: "Something is petrifying students at Hogwarts.", summary: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby." },
    { series: "Harry Potter", title: "Prisoner of Azkaban", author: "J.K. Rowling", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/HP/3.JPEG", status: "popular", tags: ["Fantasy", "Magic", "Teenagers"], description: "A dangerous prisoner has escaped from Azkaban.", summary: "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black." },
    { series: "Harry Potter", title: "Goblet of Fire", author: "J.K. Rowling", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/HP/4.JPEG", status: "hidden", tags: ["Fantasy", "Magic", "Teenagers"], description: "The Triwizard Tournament comes to Hogwarts.", summary: "Harry Potter is midway through his training as a wizard and his coming of age." },
    { series: "Harry Potter", title: "Order of the Phoenix", author: "J.K. Rowling", paws: "🐾🐾🐾🐾", image: "pictures/books/HP/5.JPEG", status: "hidden", tags: ["Fantasy", "Magic", "Teenagers"], description: "Dumbledore's Army prepares for war.", summary: "Lord Voldemort has returned, but the Ministry of Magic is doing everything it can to keep the wizarding world from knowing the truth." },
    { series: "Harry Potter", title: "Half-Blood Prince", author: "J.K. Rowling", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/HP/6.JPEG", status: "hidden", tags: ["Fantasy", "Magic", "Teenagers"], description: "Harry discovers the secret of Horcruxes.", summary: "It is the middle of the summer, but there is a strange mist pressing against the window panes." },
    { series: "Harry Potter", title: "Deathly Hallows", author: "J.K. Rowling", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/HP/7.JPEG", status: "new", tags: ["Fantasy", "Magic", "Teenagers"], description: "The final showdown with Voldemort.", summary: "Harry is waiting in Privet Drive. The Order of the Phoenix is coming to escort him safely away." },

    // SEVEN WONDERS 
    { series: "Seven Wonders", title: "The Colossus Rises", author: "Peter Lerangis", paws: "🐾🐾🐾🐾", image: "pictures/books/7wonder/1.JPEG", status: "hidden", tags: ["Adventure", "Fantasy", "Teenagers"], description: "Jack discovers he will die unless he finds the Loculi.", summary: "Jack McKinley is an ordinary kid with an extraordinary problem. In six months, he’s going to die." },
    { series: "Seven Wonders", title: "Lost in Babylon", author: "Peter Lerangis", paws: "🐾🐾🐾🐾", image: "pictures/books/7wonder/2.JPEG", status: "hidden", tags: ["Adventure", "Fantasy", "Teenagers"], description: "The search for the second Loculus in ancient Babylon.", summary: "The select group of kids must find the lost Loculus in the Hanging Gardens of Babylon." },
    { series: "Seven Wonders", title: "The Tomb of Shadows", author: "Peter Lerangis", paws: "🐾🐾🐾🐾", image: "pictures/books/7wonder/3.JPEG", status: "hidden", tags: ["Adventure", "Fantasy", "Teenagers"], description: "A journey to the Mausoleum at Halicarnassus.", summary: "Jack and his friends go into the shadows to find the next hidden treasure." },
    { series: "Seven Wonders", title: "The Curse of the King", author: "Peter Lerangis", paws: "🐾🐾🐾🐾", image: "pictures/books/7wonder/4.JPEG", status: "hidden", tags: ["Adventure", "Fantasy", "Teenagers"], description: "The race to the Temple of Artemis.", summary: "The heroes face their toughest challenge yet as the secret of the King is revealed." },
    { series: "Seven Wonders", title: "The Legend of the Rift", author: "Peter Lerangis", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/7wonder/5.JPEG", status: "new", tags: ["Adventure", "Fantasy", "Teenagers"], description: "The epic conclusion to the Seven Wonders quest.", summary: "The final battle against the forces of time and magic to save their lives." },

    //DOG MAN (First 5)
    { series: "Dog Man", title: "Dog Man", author: "Dav Pilkey", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/dogman/1.JPEG", status: "Hidden", tags: ["Kids", "Humor", "Graphic-Novel"], description: "Part Dog, Part Man, All Hero.", summary: "George and Harold have created a hidden hero who digs into deception, claws after crooks, and rolls over robbers." },
    { series: "Dog Man", title: "Unleashed", author: "Dav Pilkey", paws: "🐾🐾🐾🐾", image: "pictures/books/dogman/2.JPG", status: "popular", tags: ["Kids", "Humor", "Graphic-Novel"], description: "The mayor is in trouble and Petey is back!", summary: "Dog Man is still learning a few tricks of the trade. Petey the cat is out of the bag, and his criminal curiosity is taking the city by storm." },
    { series: "Dog Man", title: "A Tale of Two Kitties", author: "Dav Pilkey", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/dogman/3.JPEG", status: "Hidden", tags: ["Kids", "Humor", "Graphic-Novel"], description: "Dog Man meets Li'l Petey.", summary: "A cute kitten sidekick arrives, but Petey wants him to be evil." },
    { series: "Dog Man", title: "Dog Man and Cat Kid", author: "Dav Pilkey", paws: "🐾🐾🐾🐾", image: "pictures/books/dogman/4.JPG", status: "Hidden", tags: ["Kids", "Humor", "Graphic-Novel"], description: "The dynamic duo is here!", summary: "Hot diggity dog! Dog Man is back — and this time he's not alone." },
    { series: "Dog Man", title: "Lord of the Fleas", author: "Dav Pilkey", paws: "🐾🐾🐾🐾🐾", image: "pictures/books/dogman/5.JPG", status: "new", tags: ["Kids", "Humor", "Graphic-Novel"], description: "A hidden group of villains appears.", summary: "When a hidden bunch of baddies bust into town, Dog Man is called into action." },

    // CAPTAIN UNDERPANTS (Firt 3) 
    { series: "Captain Underpants", title: "The First Epic Novel", author: "Dav Pilkey", paws: "🐾🐾🐾🐾", image: "pictures/books/CU/1.JPEG", status: "hidden", tags: ["Kids", "Humor"], description: "The origin of the waist-band warrior.", summary: "George and Harold are fourth-grade best friends who love making comic books. They accidentally hypnotize their principal." },
    { series: "Captain Underpants", title: "The Talking Toilets", author: "Dav Pilkey", paws: "🐾🐾🐾🐾", image: "pictures/books/CU/2.JPEG", status: "hidden", tags: ["Kids", "Humor"], description: "George and Harold vs. carnivorous toilets.", summary: "The boys accidentally bring a pack of toilets to life during the science fair." },
    { series: "Captain Underpants", title: "The Invasion of the Incredibly Naughty Cafeteria Ladies", author: "Dav Pilkey", paws: "🐾🐾🐾🐾", image: "pictures/books/CU/3.JPEG", status: "hidden", tags: ["Kids", "Humor"], description: "Aliens are taking over the school lunchroom.", summary: "Space aliens are disguised as lunch ladies and planning to turn students into zombies." }
];
